"""
backend/app/api/v1/signals.py
API endpoints for Probabilistic Trading Signals & Setups.
"""
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from backend.app.db.session import get_db
from backend.app.schemas.signal import SignalCreate, SignalResponse, SignalUpdate
from backend.app.crud.crud_signal import crud_signal

router = APIRouter(prefix="/signals", tags=["Trading Signals & Setups"])


@router.get("/active", response_model=List[SignalResponse])
def get_active_signals(
    asset_id: Optional[int] = None,
    limit: int = 50,
    db: Session = Depends(get_db),
):
    """
    Get all active probabilistic setups with technical score, targets, and invalidations.
    """
    return crud_signal.get_active(db=db, asset_id=asset_id, limit=limit)


@router.get("/{signal_id}", response_model=SignalResponse)
def get_signal_by_id(signal_id: int, db: Session = Depends(get_db)):
    """
    Get a single signal setup with complete supporting and conflicting evidence.
    """
    signal = crud_signal.get(db=db, signal_id=signal_id)
    if not signal:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Trading signal #{signal_id} not found",
        )
    return signal


@router.post("", response_model=SignalResponse, status_code=status.HTTP_201_CREATED)
def create_signal(signal_in: SignalCreate, db: Session = Depends(get_db)):
    """
    Store an algorithmic trade setup generated by the quantitative strategy engine.
    """
    return crud_signal.create(db=db, obj_in=signal_in)


@router.post("/{signal_id}/invalidate", response_model=SignalResponse)
def invalidate_signal(
    signal_id: int,
    reason: str = "Price touched invalidation level",
    db: Session = Depends(get_db),
):
    """
    Mark a signal as INVALIDATED when market price violates the setup threshold.
    """
    signal = crud_signal.invalidate(db=db, signal_id=signal_id, reason=reason)
    if not signal:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Signal #{signal_id} not found",
        )
    return signal
